name: AdhModel

channels:
    - pyviz/label/earthsim
    - pyviz/label/dev
    - bokeh
    - erdc
    - conda-forge
    - aquaveo
    - defaults

dependencies:
    - python=3.6
    - numpy
    - pandas
    - scipy
    - netcdf4
    - jupyter
    - param>=1.9.0
    - holoviews>=1.12.3
    - datashader>=0.7.0
    - geoviews>=1.6.2
    - panel>=0.5.0
    - bokeh>=1.1.0
    - cartopy>=0.17.0
    - xarray>=0.11.0
    - colorcet>=1.0.0
    - notebook>=5.5.0
    - fiona
    - gdal>=2.3.3
    - rasterio==1.0.13
    - xmscore
    - xmsinterp
    - xmsgrid
    - xmsmesh
    - opencv
    - quest==3.1.1
    - ulmo==0.8.5
    - lancet>=0.9.0
    - param >=1.7.0
    - pyct >=0.4.4
    - setuptools >=30.3.0
    - bokeh >=1.1.0
    - pyviz_comms >=0.6.0
    - nodejs >=9.11.1
    - earthsim
    - jupyterlab
    - genesis
    # for testing
    - pytest
    - pyflakes
    - nbsmoke
