{% set data = load_setup_py_data() %}

package:
  name: AdhModel
  version: {{ data['version'] }}

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  noarch: python
  # build number only non-zero for rebuilding the same version
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  requires:
    # dependencies are defined in setup.py
    {% for dep in data['extras_require'] %}
    - {{ dep.lower() }}
    {% endfor %}
  imports:
    - AdhModel
    - AdhModel.simulation

about:
  home: {{ data['url'] }}
  summary: {{ data['description'] }}